version: '3.1'

services:

  backend:
    container_name: blog-nestjs-app
    build: ./
    env_file: ./.env.development
    ports:
      - 5000:5000
    environment:
      - SECRET=123456
      - EXP_IN_REFRESH_TOKEN=1d
      - EXP_IN_ACCESS_TOKEN=1h
      - CLOUDINARY_NAME=darzhlzpy
      - CLOUDINARY_API_KEY=334258369538565
      - CLOUDINARY_API_SECRET=pygBOLxX2wBflpuDzyewy82N0CQ
      - NODE_ENV=local
      - DATABASE_PORT=33061
      - DATABASE_HOST=host.docker.internal
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - PORT=5000
    networks:
      - default

# username: root
# password: root
